spring.application.name=TaskForge

# Render provides PORT automatically
server.port=${PORT:9090}

# MongoDB (use env var on Render)
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:taskforge}

# Swagger UI
springdoc.swagger-ui.path=/swagger

# JWT
jwt.secret=${JWT_SECRET:THIS_IS_A_SUPER_LONG_SECRET_KEY_32_CHARS_MINIMUM_123456}
jwt.expirationMs=${JWT_EXPIRATION_MS:86400000}

# Logs (keep INFO, switch to DEBUG only when needed)
logging.level.org.springframework.boot.autoconfigure.mongo=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO