spring.application.name=TaskForge

server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI}

springdoc.swagger-ui.path=/swagger

jwt.secret=${JWT_SECRET:THIS_IS_A_SUPER_LONG_SECRET_KEY_32_CHARS_MINIMUM_123456}
jwt.expirationMs=${JWT_EXPIRATION_MS:86400000}

logging.level.org.springframework.boot.autoconfigure.mongo=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO