spring.application.name=TaskForge
server.port=9090

spring.data.mongodb.uri=mongodb+srv://TaskForge:Prayas1110@cluster0.t1ktek3.mongodb.net/taskforge?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=taskforge

springdoc.swagger-ui.path=/swagger

jwt.secret=THIS_IS_A_SUPER_LONG_SECRET_KEY_32_CHARS_MINIMUM_123456
jwt.expirationMs=86400000

logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


logging.level.org.springframework.boot.context.properties=DEBUG